export const LAYOUT = {
  SIDEBAR_WIDTH: 280,
  SIDEBAR_MIN_WIDTH: 200,
  SIDEBAR_MAX_WIDTH: 400,
  DETAIL_PANEL_WIDTH: 340,
  DETAIL_PANEL_MIN_WIDTH: 300,
  DETAIL_PANEL_MAX_WIDTH: 600,
  HEADER_HEIGHT: 56,
  VIEW_TABS_HEIGHT: 48,
  FILTER_BAR_HEIGHT: 44,
  TABLE_HEADER_HEIGHT: 40,
  TABLE_ROW_HEIGHT: 44,
  BOARD_COLUMN_WIDTH: 340,
  BOARD_CARD_MIN_HEIGHT: 100,
  ROADMAP_TASK_LIST_WIDTH: 340,
  ROADMAP_ROW_HEIGHT: 52,
  GANTT_BAR_HEIGHT: 24,
} as const;

export const TABLE_COLUMNS = {
  CHECKBOX_WIDTH: 40,
  ID_WIDTH: 110,
  MIN_COLUMN_WIDTH: 80,
  DEFAULT_WIDTHS: {
    text: 200,
    number: 100,
    single_select: 120,
    multi_select: 150,
    date: 120,
    person: 150,
    reference: 200,
  },
} as const;

export const ANIMATION = {
  PANEL_TRANSITION: 200,
  DRAG_TRANSITION: 150,
  HOVER_DELAY: 400,
} as const;

export const Z_INDEX = {
  TABLE_HEADER: 10,
  DRAG_OVERLAY: 100,
  DROPDOWN: 50,
  MODAL_BACKDROP: 200,
  MODAL: 201,
} as const;
