.PHONY: help proto clean dev run install db-up db-down db-reset db-logs

help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Available targets:'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

install: ## Install all dependencies
	@echo "Installing Python dependencies..."
	uv sync
	@echo "Installing UI dependencies..."
	cd src/ui && pnpm install
	@echo "Done!"

proto: ## Generate all protobuf code (backend + UI)
	@echo "Generating protobuf code..."
	rm -rf src/uwos/gen src/ui/src/gen
	PATH="$(PWD)/src/ui/node_modules/.bin:$(PATH)" buf generate
	printf "import os\nimport sys\n\nsys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))\n" > src/uwos/gen/__init__.py
	@# Create __init__.py for all generated proto packages
	@for pkg in auth notes search settings bookmarks permissions common groups organizations users cal; do \
		touch src/uwos/gen/$$pkg/__init__.py 2>/dev/null || true; \
		touch src/uwos/gen/$$pkg/v1/__init__.py 2>/dev/null || true; \
	done
	@echo "Protobuf code generated for backend and UI!"

clean: ## Clean generated files
	@echo "Cleaning generated files..."
	rm -rf src/uwos/gen src/ui/src/gen
	rm -rf src/uwos/__pycache__ src/uwos/**/__pycache__
	rm -rf src/ui/dist src/ui/node_modules/.vite
	@echo "Cleaned!"

db-shell: ## Connect to database shell
	docker-compose exec postgres psql -U uwos -d uwos

db-migrate: ## Run migrations
	uv run alembic -c src/uwos/alembic.ini upgrade head

dev: ## Run both backend and frontend in development mode
	@echo "Starting development servers..."
	@echo "Backend: http://0.0.0.0:8000"
	@echo "Frontend: http://0.0.0.0:5173"
	@trap 'kill 0' EXIT; \
	uv run -m uwos.main & \
	cd src/ui && pnpm dev

run: ## Run backend server only
	uv run -m uwos.main

ui: ## Run frontend dev server only
	cd src/ui && pnpm dev

build-ui: ## Build frontend for production
	cd src/ui && pnpm build

lint: ## Run linters
	uv run ruff check src/uwos/ --exclude src/uwos/gen --fix
	cd src/ui && pnpm run lint

format: ## Format code
	uv run ruff format src/uwos/ --exclude src/uwos/gen

test: ## Run tests
	uv run pytest

licenses: ## Generate third-party license files
	@echo "Generating third-party licenses..."
	@echo "# Third-Party Licenses\n\nThis file lists all third-party dependencies used in UWOS and their licenses.\n\nThis file is auto-generated by running \`make licenses\`.\n\n## Python Dependencies\n" > docs/LICENSES.md
	uv run pip-licenses --format=markdown --with-urls --ignore-packages uwos >> docs/LICENSES.md
	@echo "\n## Node.js Dependencies\n" >> docs/LICENSES.md
	@echo "| Package | License | Homepage |" >> docs/LICENSES.md
	@echo "|---------|---------|----------|" >> docs/LICENSES.md
	cd src/ui && pnpm licenses list --prod --json 2>/dev/null | node -e "const d=require('fs').readFileSync(0,'utf8');const j=JSON.parse(d);const rows=[];Object.entries(j).forEach(([lic,pkgs])=>pkgs.forEach(p=>rows.push([p.name+'@'+p.versions[0],lic,p.homepage||''])));rows.sort((a,b)=>a[0].localeCompare(b[0])).forEach(r=>console.log('| '+r[0]+' | '+r[1]+' | '+r[2]+' |'));" >> ../../docs/LICENSES.md
	@echo "Third-party licenses generated in docs/LICENSES.md"

.DEFAULT_GOAL := help
