export { calendarReducer } from '@/features/calendar/store/calendarSlice';
export { calendarUiReducer } from '@/features/calendar/store/calendarUiSlice';

export {
  fetchEventsInRange,
  fetchEvent,
  createEvent,
  updateEvent as updateEventThunk,
  deleteEvent,
  fetchCategories,
  createCategory,
  updateCategory as updateCategoryThunk,
  deleteCategory,
  updateAttendeeStatus,
  addAttendees,
  removeAttendees,
} from '@/features/calendar/store/calendarThunks';

export {
  setEvents,
  addEvent,
  updateEvent,
  removeEvent,
  addCategory,
  updateCategory,
  removeCategory,
  setFilters,
  clearFilters,
  setSearchQuery,
  toggleCategoryFilter,
  toggleTagFilter,
  setEventsLoading,
  setCreatingLoading,
  setUpdatingLoading,
  setDeletingLoading,
  setEventsError,
  setCreatingError,
  clearErrors,
  setPagination,
  resetCalendarState,
} from '@/features/calendar/store/calendarSlice';

export {
  setViewMode,
  setCurrentDate,
  goToToday,
  setQuickAccessFilter,
  selectEvent,
  deselectEvent,
  toggleDetailPanel,
  openDetailPanel,
  closeDetailPanel,
  setDetailViewMode,
  setDetailPanelWidth,
  setActiveDetailTab,
  openEventModal,
  closeEventModal,
  openEditEvent,
  closeEditEvent,
  toggleSidebar,
  setSidebarCollapsed,
  setSidebarWidth,
  toggleSectionCollapse,
  setSectionCollapsed,
  startDrag,
  setDropTarget,
  endDrag,
  setDisplayTimezone,
  toggleTravelingMode,
  setTravelingMode,
  openQuickCapture,
  closeQuickCapture,
  openTimezoneModal,
  closeTimezoneModal,
  openAddCategoryModal,
  openEditCategoryModal,
  closeAddCategoryModal,
  openCreateTemplateModal,
  openEditTemplateModal,
  closeCreateTemplateModal,
  setMobileView,
  setActiveMobilePanel,
  resetCalendarUiState,
} from '@/features/calendar/store/calendarUiSlice';
