/**
 * MindMapEdge - Colored bezier edge for mind map branches.
 *
 * Auto-generated by the layout algorithm. Not user-selectable.
 * Uses the branch color from edge data for consistent branch coloring.
 */

import {
  BaseEdge,
  getBezierPath,
  type EdgeProps,
  type Edge,
} from '@xyflow/react';
import type { MindMapEdgeData } from '@/features/notes/canvas/types';

type MindMapEdgeType = Edge<MindMapEdgeData>;

const DEFAULT_COLOR = 'hsl(var(--muted-foreground) / 0.4)';
const STROKE_WIDTH = 2.5;

export function MindMapEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  data,
}: EdgeProps<MindMapEdgeType>) {
  const edgeData = data as MindMapEdgeData | undefined;
  const color = edgeData?.branchColor || DEFAULT_COLOR;

  const [path] = getBezierPath({
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
  });

  return (
    <BaseEdge
      id={id as string}
      path={path}
      style={{
        stroke: color,
        strokeWidth: STROKE_WIDTH,
        fill: 'none',
      }}
    />
  );
}
