"""initial_login_schema

Revision ID: 001
Revises:
Create Date: 2026-01-08 03:25:19.214381

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("plan", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("max_members", sa.Integer(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_organizations_domain"), "login_organizations", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_login_organizations_slug"), "login_organizations", ["slug"], unique=True
    )
    op.create_table(
        "login_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system_admin", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_users_email"), "login_users", ["email"], unique=True)
    op.create_index(op.f("ix_login_users_username"), "login_users", ["username"], unique=True)
    op.create_table(
        "login_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["login_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["login_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_groups_organization_id"), "login_groups", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_login_groups_slug"), "login_groups", ["slug"], unique=False)
    op.create_table(
        "login_organization_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "MEMBER", name="organizationrole"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["login_organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["login_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_organization_members_organization_id"),
        "login_organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_organization_members_user_id"),
        "login_organization_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "login_sso_configurations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("SAML", "OIDC", "GOOGLE", "MICROSOFT", "OKTA", name="ssoprovider"),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("enforce_sso", sa.Boolean(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("metadata_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("sso_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("certificate", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("client_secret", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["login_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_sso_configurations_organization_id"),
        "login_sso_configurations",
        ["organization_id"],
        unique=True,
    )
    op.create_table(
        "login_group_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "MEMBER", name="grouprole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["login_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["login_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_group_members_group_id"), "login_group_members", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_login_group_members_user_id"), "login_group_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_group_members_user_id"), table_name="login_group_members")
    op.drop_index(op.f("ix_login_group_members_group_id"), table_name="login_group_members")
    op.drop_table("login_group_members")
    op.drop_index(
        op.f("ix_login_sso_configurations_organization_id"), table_name="login_sso_configurations"
    )
    op.drop_table("login_sso_configurations")
    op.drop_index(
        op.f("ix_login_organization_members_user_id"), table_name="login_organization_members"
    )
    op.drop_index(
        op.f("ix_login_organization_members_organization_id"),
        table_name="login_organization_members",
    )
    op.drop_table("login_organization_members")
    op.drop_index(op.f("ix_login_groups_slug"), table_name="login_groups")
    op.drop_index(op.f("ix_login_groups_organization_id"), table_name="login_groups")
    op.drop_table("login_groups")
    op.drop_index(op.f("ix_login_users_username"), table_name="login_users")
    op.drop_index(op.f("ix_login_users_email"), table_name="login_users")
    op.drop_table("login_users")
    op.drop_index(op.f("ix_login_organizations_slug"), table_name="login_organizations")
    op.drop_index(op.f("ix_login_organizations_domain"), table_name="login_organizations")
    op.drop_table("login_organizations")
    # ### end Alembic commands ###

    # Drop enums
    sa.Enum("OWNER", "ADMIN", "MEMBER", name="organizationrole").drop(op.get_bind(), checkfirst=True)
    sa.Enum("ADMIN", "MEMBER", name="grouprole").drop(op.get_bind(), checkfirst=True)
    sa.Enum("SAML", "OIDC", "GOOGLE", "MICROSOFT", "OKTA", name="ssoprovider").drop(
        op.get_bind(), checkfirst=True
    )
