"""Add content permission system and visibility scopes

Revision ID: 005
Revises: 004
Create Date: 2026-01-09 04:14:58.382497

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Create enum types first (before tables that use them)

    # Create visibilityscope enum if it doesn't exist
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'visibilityscope'")
    ).scalar()
    if not result:
        visibility_enum = postgresql.ENUM(
            "PRIVATE", "GROUP", "ORGANIZATION", "PUBLIC", name="visibilityscope"
        )
        visibility_enum.create(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions_content_permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "NOTE",
                "FILE",
                "CALENDAR_EVENT",
                "BOOK",
                "PASSWORD",
                "WORKFLOW",
                "CHAT_MESSAGE",
                "SPACE",
                name="contenttype",
            ),
            nullable=False,
        ),
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum("USER", "GROUP", "ORGANIZATION", name="subjecttype"),
            nullable=False,
        ),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column(
            "permission_level",
            sa.Enum("VIEW", "EDIT", "ADMIN", "OWNER", name="permissionlevel"),
            nullable=False,
        ),
        sa.Column("can_view", sa.Boolean(), nullable=False),
        sa.Column("can_edit", sa.Boolean(), nullable=False),
        sa.Column("can_delete", sa.Boolean(), nullable=False),
        sa.Column("can_share", sa.Boolean(), nullable=False),
        sa.Column("can_move", sa.Boolean(), nullable=False),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["login_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["login_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permissions_content_permissions_content_id"),
        "permissions_content_permissions",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_content_permissions_content_type"),
        "permissions_content_permissions",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_content_permissions_organization_id"),
        "permissions_content_permissions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_content_permissions_subject_id"),
        "permissions_content_permissions",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_content_permissions_subject_type"),
        "permissions_content_permissions",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "permissions_content_group_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "NOTE",
                "FILE",
                "CALENDAR_EVENT",
                "BOOK",
                "PASSWORD",
                "WORKFLOW",
                "CHAT_MESSAGE",
                "SPACE",
                name="contenttype",
            ),
            nullable=False,
        ),
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("linked_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["login_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linked_by_user_id"],
            ["login_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["login_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permissions_content_group_links_content_id"),
        "permissions_content_group_links",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_content_group_links_content_type"),
        "permissions_content_group_links",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_content_group_links_group_id"),
        "permissions_content_group_links",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_content_group_links_organization_id"),
        "permissions_content_group_links",
        ["organization_id"],
        unique=False,
    )
    op.alter_column(
        "login_users",
        "font_family",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="User's preferred font family: 'inter', 'geist', or 'system'",
        existing_nullable=True,
    )
    op.add_column("notes_notes", sa.Column("owner_id", sa.Uuid(), nullable=False))
    op.add_column(
        "notes_notes",
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "GROUP", "ORGANIZATION", "PUBLIC", name="visibilityscope"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_notes_notes_created_by"), table_name="notes_notes")
    op.create_index(op.f("ix_notes_notes_owner_id"), "notes_notes", ["owner_id"], unique=False)
    op.create_index(op.f("ix_notes_notes_visibility"), "notes_notes", ["visibility"], unique=False)
    op.drop_constraint(op.f("notes_notes_created_by_fkey"), "notes_notes", type_="foreignkey")
    op.create_foreign_key(None, "notes_notes", "login_users", ["owner_id"], ["id"])
    op.drop_column("notes_notes", "created_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes_notes", sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "notes_notes", type_="foreignkey")
    op.create_foreign_key(
        op.f("notes_notes_created_by_fkey"), "notes_notes", "login_users", ["created_by"], ["id"]
    )
    op.drop_index(op.f("ix_notes_notes_visibility"), table_name="notes_notes")
    op.drop_index(op.f("ix_notes_notes_owner_id"), table_name="notes_notes")
    op.create_index(op.f("ix_notes_notes_created_by"), "notes_notes", ["created_by"], unique=False)
    op.drop_column("notes_notes", "visibility")
    op.drop_column("notes_notes", "owner_id")
    op.alter_column(
        "login_users",
        "font_family",
        existing_type=sa.VARCHAR(length=20),
        comment="User's preferred font family: 'inter', 'geist', or 'system'",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_permissions_content_group_links_organization_id"),
        table_name="permissions_content_group_links",
    )
    op.drop_index(
        op.f("ix_permissions_content_group_links_group_id"),
        table_name="permissions_content_group_links",
    )
    op.drop_index(
        op.f("ix_permissions_content_group_links_content_type"),
        table_name="permissions_content_group_links",
    )
    op.drop_index(
        op.f("ix_permissions_content_group_links_content_id"),
        table_name="permissions_content_group_links",
    )
    op.drop_table("permissions_content_group_links")
    op.drop_index(
        op.f("ix_permissions_content_permissions_subject_type"),
        table_name="permissions_content_permissions",
    )
    op.drop_index(
        op.f("ix_permissions_content_permissions_subject_id"),
        table_name="permissions_content_permissions",
    )
    op.drop_index(
        op.f("ix_permissions_content_permissions_organization_id"),
        table_name="permissions_content_permissions",
    )
    op.drop_index(
        op.f("ix_permissions_content_permissions_content_type"),
        table_name="permissions_content_permissions",
    )
    op.drop_index(
        op.f("ix_permissions_content_permissions_content_id"),
        table_name="permissions_content_permissions",
    )
    op.drop_table("permissions_content_permissions")
    # ### end Alembic commands ###
