"""add pg_trgm and search_index and node refs

Revision ID: 006
Revises: 005
Create Date: 2026-01-11 06:49:45.821745

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_index",
        sa.Column("urn", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("keywords", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("shared_group_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("shared_user_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rank_score", sa.FLOAT(), server_default="1.0", nullable=True),
        sa.PrimaryKeyConstraint("urn"),
    )
    op.create_index(
        op.f("ix_search_index_organization_id"), "search_index", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_search_index_visibility"), "search_index", ["visibility"], unique=False)
    op.add_column(
        "notes_notes",
        sa.Column("outgoing_references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )

    # 1. Trigram index for fuzzy search on 'keywords'
    op.create_index(
        "ix_search_trgm",
        "search_index",
        ["keywords"],
        postgresql_using="gin",
        postgresql_ops={"keywords": "gin_trgm_ops"},
    )

    # 2. GIN index for fast permission array overlaps
    op.create_index(
        "ix_search_perm",
        "search_index",
        ["shared_group_ids", "shared_user_ids"],
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes_notes", "outgoing_references")
    op.drop_index(op.f("ix_search_index_visibility"), table_name="search_index")
    op.drop_index(op.f("ix_search_index_organization_id"), table_name="search_index")
    op.drop_table("search_index")
    # ### end Alembic commands ###
