"""Permission checking utilities for content access control."""

from uniffy.core.auth.permissions.audit import (
    record_access_mode_changed,
    record_baseline_role_changed,
    record_member_added,
    record_member_removed,
    record_member_role_changed,
    record_ownership_transferred,
)
from uniffy.core.auth.permissions.checker import PermissionChecker
from uniffy.core.auth.permissions.defaults import (
    modes_at_least_as_open,
    resolve_access_policy,
    resolve_content_defaults,
    resolve_effective_policy,
)
from uniffy.core.auth.permissions.helpers import (
    require_delete,
    require_edit,
    require_manage,
    require_transfer,
    require_view,
)
from uniffy.core.auth.permissions.queries import ContentAccessQuery
from uniffy.core.auth.permissions.roles import (
    MIN_FOR_COMMENT,
    MIN_FOR_DELETE,
    MIN_FOR_EDIT,
    MIN_FOR_MANAGE,
    MIN_FOR_TRANSFER,
    MIN_FOR_VIEW,
    ROLE_ORDINAL,
    max_role,
    role_can_comment,
    role_can_delete,
    role_can_edit,
    role_can_manage,
    role_can_transfer,
    role_can_view,
    role_is_higher_than,
)
from uniffy.core.auth.permissions.visible_sets import (
    compute_visible_content_ids_by_type,
    compute_visible_tag_ids,
    get_visible_content_ids_by_type,
    get_visible_tag_ids,
    invalidate_visible_sets_for_org,
    invalidate_visible_sets_for_user,
    invalidate_visible_sets_for_user_global,
)

__all__ = [
    "ContentAccessQuery",
    "MIN_FOR_COMMENT",
    "MIN_FOR_DELETE",
    "MIN_FOR_EDIT",
    "MIN_FOR_MANAGE",
    "MIN_FOR_TRANSFER",
    "MIN_FOR_VIEW",
    "PermissionChecker",
    "ROLE_ORDINAL",
    "compute_visible_content_ids_by_type",
    "compute_visible_tag_ids",
    "get_visible_content_ids_by_type",
    "get_visible_tag_ids",
    "invalidate_visible_sets_for_org",
    "invalidate_visible_sets_for_user",
    "invalidate_visible_sets_for_user_global",
    "max_role",
    "modes_at_least_as_open",
    "record_access_mode_changed",
    "record_baseline_role_changed",
    "record_member_added",
    "record_member_removed",
    "record_member_role_changed",
    "record_ownership_transferred",
    "resolve_access_policy",
    "resolve_content_defaults",
    "resolve_effective_policy",
    "require_delete",
    "require_edit",
    "require_manage",
    "require_transfer",
    "require_view",
    "role_can_comment",
    "role_can_delete",
    "role_can_edit",
    "role_can_manage",
    "role_can_transfer",
    "role_can_view",
    "role_is_higher_than",
]
