import React, { useCallback, useEffect, useRef, useState } from "react";
import { View, Text, StyleSheet, type StyleProp, type ViewStyle } from "react-native";
import { Image } from "expo-image";
import { FILE_COLORS } from "@theme/theme";
import { FONT } from "@theme/typography";
import { buildThumbnailUrl, assetAuthHeaders, supportsThumbnail } from "@features/files/fileUrls";

// Thumbnails are generated by a background worker AFTER upload completes, so a
// freshly-uploaded image 404s for a few seconds. Retry a bounded number of times
// (with a delay) before settling on the extension badge.
const MAX_RETRIES = 4;
const RETRY_MS = 2500;

function fileColor(ext: string): string {
  return FILE_COLORS[ext.toLowerCase()] ?? FILE_COLORS.default;
}

/**
 * File preview tile for list/grid rows: renders the server-generated thumbnail
 * for image/pdf/video files and falls back to a colored extension badge for
 * everything else (or when the thumbnail is missing / not yet generated).
 */
export function FileThumb({
  fileId,
  organizationId,
  mimeType,
  ext,
  style,
  radius = 12,
  textSize = 10,
  refreshKey,
}: {
  fileId: string;
  organizationId?: string | null;
  mimeType?: string;
  ext: string;
  style?: StyleProp<ViewStyle>;
  radius?: number;
  textSize?: number;
  // Bump to force a fresh thumbnail attempt (e.g. the list's pull-to-refresh).
  refreshKey?: number;
}) {
  const [failed, setFailed] = useState(false);
  const [tick, setTick] = useState(0);
  const attemptsRef = useRef(0);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const color = fileColor(ext);
  const tint = color + "18";

  // A recycled row (or a refresh) should re-attempt from scratch.
  useEffect(() => {
    attemptsRef.current = 0;
    setFailed(false);
    setTick(0);
  }, [fileId, refreshKey]);

  useEffect(
    () => () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    },
    [],
  );

  const handleError = useCallback(() => {
    if (timerRef.current) clearTimeout(timerRef.current);
    if (attemptsRef.current >= MAX_RETRIES) {
      setFailed(true);
      return;
    }
    attemptsRef.current += 1;
    // Bumping `tick` changes the URL (cache-bust) so expo-image re-fetches; the
    // delay gives the worker time to finish generating the thumbnail.
    timerRef.current = setTimeout(() => setTick((t) => t + 1), RETRY_MS);
  }, []);

  const canThumbnail = !!organizationId && supportsThumbnail(mimeType) && !failed;

  if (canThumbnail) {
    const base = buildThumbnailUrl(organizationId!, fileId);
    const uri = tick > 0 ? `${base}?r=${tick}` : base;
    return (
      <View style={[style, { borderRadius: radius, overflow: "hidden", backgroundColor: tint }]}>
        <Image
          source={{ uri, headers: assetAuthHeaders() }}
          style={StyleSheet.absoluteFill}
          contentFit="cover"
          transition={120}
          cachePolicy="memory-disk"
          onError={handleError}
        />
      </View>
    );
  }

  return (
    <View
      style={[
        style,
        {
          borderRadius: radius,
          backgroundColor: tint,
          alignItems: "center",
          justifyContent: "center",
        },
      ]}
    >
      <Text style={[styles.ext, { color, fontSize: textSize }]}>{ext.toUpperCase() || "FILE"}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  ext: { fontFamily: FONT.bold, letterSpacing: 0.5 },
});
